# Site settings
title: Frank's Blog
SEOTitle: Frank's Blog
header-img: img/post-bg-desk.jpg
email: imzhixun@gmail.com
description: "Every failure is leading towards success."
keyword: "Frank, Frank's Blog, Yuzhixun, PHP, Flutter, Golang, Apple, Macbook Pro, iPhone"
url: "http://szfrank.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/szfrank/szfrank.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-frank-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     Yuzhixun
zhihu_username:     yuzhixun
github_username:    szfrank
facebook_username:  ifrankyu
jianshu_username:   87ed2f9eb91b
#twitter_username:   Yuzhixun




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: frankyu

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 6e8cfac81df3bb22b7c4   #生成的clientID
  clientSecret: 8c16700e24fbceeea0b29be4f974e6b1a49a1082  #生成的clientSecret
  repo: szfrank.github.io    #仓库名称
  owner: ifrankyu    #github用户名
  admin: ifrankyu
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: xxxxxxxxx

# Google Analytics
ga_track_id: 'UA-90855596xxx-1'            # Format: UA-xxxxxx-xx
ga_domain: auto # szfrank.github.io 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Github.Frank",
        href: "https://github.com/szfrank"
    },
    {
        title: "简书·Frank",
        href: "https://www.jianshu.com/u/87ed2f9eb91b"
    },{
        title: "Flutter",
        href: "https://flutter.dev/"
    },{
        title: "Google",
        href: "https://www.google.com/"
    }
]
